//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1_Wumpus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Team1_Wumpus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream background {
            get {
                return ResourceManager.GetStream("background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream bat {
            get {
                return ResourceManager.GetStream("bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream scream {
            get {
                return ResourceManager.GetStream("scream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	25	26	2	7	6	30
        ///2	26	3	9	8	7	1
        ///3	27	28	4	9	2	26
        ///4	28	5	11	10	9	3
        ///5	29	30	6	11	4	28
        ///6	30	1	7	12	11	5
        ///7	1	2	8	13	12	6
        ///8	2	9	15	14	13	7
        ///9	3	4	10	15	8	2
        ///10	4	11	17	16	15	9
        ///11	5	6	12	17	10	4
        ///12	6	7	13	18	17	11
        ///13	7	8	14	19	18	12
        ///14	8	15	21	20	19	13
        ///15	9	10	16	21	14	8
        ///16	10	17	23	22	21	15
        ///17	11	12	18	23	16	10
        ///18	12	13	19	24	23	17
        ///19	13	14	20	25	24	18
        ///20	14	21	27	26	25	19
        ///21	15	16	22	27	20	14
        ///22	16	23	29	28	27	21
        ///23	17	18	24	29	22	16
        ///24	18	19	25	30	29	23
        ///25	19	20	26	1	30	24
        ///26	20	27	3	2	1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string system0 {
            get {
                return ResourceManager.GetString("system0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	0	0	0	7	0	0
        ///
        ///2	0	3	0	8	0	0
        ///
        ///3	0	0	4	9	0	0
        ///
        ///4	0
        ///	5	0	10	0	0
        ///5	0	0	0	11	4	0
        ///6	0	1	0	12	0	0
        ///
        ///7	1	0	0	13	0	0
        ///8	2	0	0	14	0	0
        ///
        ///9	3	0	0	15	0	0
        ///
        ///10	4	0	0	16	0	0
        ///11	5	0	0	17	0	0	
        ///12	6	0	0	18	0	0
        ///13	7	0	0	19	0	0
        ///14	8	0	0	20	0	0
        ///15	9	0	0	21	0	0
        ///16	10	0	0	22	0	0
        ///17	11	0	0	23	0	0
        ///18	12	0	0	24	0	0
        ///19	13	0	0	25	0	0
        ///20	14	0	0	26	0	0
        ///21	15	0	0	27	0	0
        ///22	16	0	0	28	0	0
        ///23	17	0	0	29	0	0
        ///24	18	0	0	30	0	0
        ///25	19	0	26	0	0	0
        ///26	20	0	0	0	0	25
        ///27	21	0	28	0	0	0
        ///28	22	0	0	0	0	27
        ///29	23	0	30	0	0	0
        ///30 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string system1 {
            get {
                return ResourceManager.GetString("system1", resourceCulture);
            }
        }
    }
}
